# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-LastFM-SimilarArtists
version:      0.01
version_from: lib/WebService/LastFM/SimilarArtists.pm
installdirs:  site
requires:
    Cache::File:                   0
    Carp:                          0
    File::Path:                    0
    LWP::Simple:                   0
    Test::Simple:                  0
    URI::Escape:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
