--- #YAML:1.0
name:               WebService-LastFM-SimilarArtists
version:            0.03
abstract:           Module to retrieve Related Artist information from audioscrobbler.net (last.fm)
author:
    - M. Blom (blom@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::File:   0
    Carp:          0
    File::Path:    0
    LWP::Simple:   0
    Test::Simple:  0
    URI::Escape:   0
    XML::Simple:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
